name: C/C++ CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sudo apt update
                  sudo apt install -y mingw-w64
                  wget https://curl.se/windows/dl-8.11.0_4/curl-8.11.0_4-win64-mingw.zip
                  sudo unzip curl-8.11.0_4-win64-mingw.zip -d /usr/local/mingw64
                  echo "CURL_INCLUDE_PATH=/usr/local/mingw64/curl-8.11.0_4-win64-mingw/include" >> $GITHUB_ENV
                  echo "CURL_LIB_PATH=/usr/local/mingw64/curl-8.11.0_4-win64-mingw/lib" >> $GITHUB_ENV

            - name: Create build directory
              run: mkdir -p build

            - name: Compile http.c
              run: x86_64-w64-mingw32-gcc -Iinclude -I$CURL_INCLUDE_PATH -c src/http.c -o build/http.o

            - name: Compile main.c
              run: x86_64-w64-mingw32-gcc -Iinclude -I$CURL_INCLUDE_PATH -c src/main.c -o build/main.o

            - name: Compile additional sources
              run: |
                  if [ -f src/uid.c ]; then x86_64-w64-mingw32-gcc -Iinclude -I$CURL_INCLUDE_PATH -c src/uid.c -o build/uid.o; fi
                  if [ -f src/computer_info.c ]; then x86_64-w64-mingw32-gcc -Iinclude -I$CURL_INCLUDE_PATH -c src/computer_info.c -o build/computer_info.o; fi
                  if [ -f src/another_source.c ]; then x86_64-w64-mingw32-gcc -Iinclude -I$CURL_INCLUDE_PATH -c src/another_source.c -o build/another_source.o; fi

            - name: Link objects and create executable
              run: |
                  OBJECTS="build/http.o build/main.o"
                  if [ -f build/uid.o ]; then OBJECTS="$OBJECTS build/uid.o"; fi
                  if [ -f build/computer_info.o ]; then OBJECTS="$OBJECTS build/computer_info.o"; fi
                  if [ -f build/another_source.o ]; then OBJECTS="$OBJECTS build/another_source.o"; fi
                  x86_64-w64-mingw32-gcc $OBJECTS -o build/main.exe -L$CURL_LIB_PATH -lcurl -lole32 -luuid

            - name: Clean up object files
              run: |
                  rm -f build/*.o
