name: C/C++ CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sudo apt update
                  sudo apt install -y mingw-w64
                  wget https://curl.se/windows/dl-7.79.1_2/curl-7.79.1_2-win64-mingw.zip
                  unzip curl-7.79.1_2-win64-mingw.zip -d /usr/local/mingw64
                  export CURL_INCLUDE_PATH=/usr/local/mingw64/curl-7.79.1_2-win64-mingw/include
                  export CURL_LIB_PATH=/usr/local/mingw64/curl-7.79.1_2-win64-mingw/lib

            - name: Create build directory
              run: mkdir -p build

            - name: Compile http.c
              run: x86_64-w64-mingw32-gcc -Iinclude -I$CURL_INCLUDE_PATH -c src/http.c -o build/http.o

            - name: Compile main.c
              run: x86_64-w64-mingw32-gcc -Iinclude -I$CURL_INCLUDE_PATH -c src/main.c -o build/main.o

            - name: Link objects and create executable
              run: x86_64-w64-mingw32-gcc build/http.o build/main.o -o build/main.exe -L$CURL_LIB_PATH -lcurl -lole32 -luuid

            - name: Clean up object files
              run: |
                  rm build/main.o
                  rm build/http.o
